import { NavBar } from "@/components/navbar/NavBar";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "KayFs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <NavBar/>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
